### PR TITLE
build: update to zig 0.13.0-dev.211+6a65561e3

### PR DESCRIPTION
**Pull request by theoparis**
I updated this project to the latest zig master, however I noticed that ziglyph is not maintained (replaced by zg) after making a PR to update it. I would have to make a PR to zg as well so I decided to just use my ziglyph fork for the time being until zg is updated.

There also seems to be a weird I/O bug going on with this PR, maybe someone can help me figure out what is wrong.

### CODE REVIEW

**Comment by natecraddock** [comment]
Sorry for the delay on this, I've been swamped the last month. I'll take a closer look later today / over the next few days and get back to you. Thanks for contributing!

**Comment by bodemann** [comment]
Thx @theoparis.  I was not able to compile the latest source with 0.11, 0.12 or master. It compiles with your changes on master, but for me the "search after each typed letter" function is not working anymore. It does work with the latest release binary.

**Comment by natecraddock** [comment]
Before fixing zf for zig master, I first need to make a release targeting zig 0.12.0 (see https://github.com/natecraddock/zf/issues/62) so package repos have a stable version to build against

After that I'll get master in a good state

**Comment by natecraddock** [comment]
This is a good foundation actually for both 0.12.0 and 0.13.0. I'll merge it in and immediately add a fix commit for terminal raw mode (I tried pushing to your theoparis/zf main but it didn't let me and I'm too lazy to figure out why at the moment)

**Pull request merged**
