### PR TITLE
Add missing top-level 'paths' field to fix build

### PR DESCRIPTION
**Pull request by arrufat**
Add missing top-level 'paths' field to fix build

### CODE REVIEW

**Comment by natecraddock** [comment]
Thanks for catching this! I go through bursts of development and then times like this where I am focused on other projects and I'm not as up-to-date on Zig dev right now.

Looks like it also needs a few changes for the recent local variable mutation checks, and there are also some issues with ziglyph. I will need to make a PR to fix a ziglyph issue, so the fix will depend on that.

Are you using a dev version of Zig where all you need is the `.paths` field? If so, I'm happy to merge this as-is so you can have that resolved, and then all of my additional fixes for the latest zig compiler can go in another commit.

**Comment by arrufat** [comment]
No, it requires some extra `var` to `const` changes.

After that, the error comes from Ziglyph, because it's using `std.mem.copy` instead of the new builtin `@memcpy`. So maybe we need to update Ziglyph first, and then this package.

**Comment by arrufat** [comment]
So, maybe we can close this PR and make a new one that fixes the build with dev version

**Comment by natecraddock** [comment]
I've already started a PR for Ziglyph and I'll add my changes on top of this PR

**Comment by natecraddock** [comment]
Ziglyph PR: https://codeberg.org/dude_the_builder/ziglyph/pulls/3

**Comment by arrufat** [comment]
Great!

**Comment by natecraddock** [comment]
Thanks again for bringing this to my attention!

**Comment by arrufat** [comment]
Thank you for updating everything so quickly!

**Pull request merged**
